// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: api/v1/product_reviews.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductReviewsService_CreateProduct_FullMethodName         = "/api.v1.ProductReviewsService/CreateProduct"
	ProductReviewsService_GetProductByID_FullMethodName        = "/api.v1.ProductReviewsService/GetProductByID"
	ProductReviewsService_EditProduct_FullMethodName           = "/api.v1.ProductReviewsService/EditProduct"
	ProductReviewsService_DeleteProduct_FullMethodName         = "/api.v1.ProductReviewsService/DeleteProduct"
	ProductReviewsService_ListProducts_FullMethodName          = "/api.v1.ProductReviewsService/ListProducts"
	ProductReviewsService_CreateReview_FullMethodName          = "/api.v1.ProductReviewsService/CreateReview"
	ProductReviewsService_GetReviewsByProductID_FullMethodName = "/api.v1.ProductReviewsService/GetReviewsByProductID"
	ProductReviewsService_EditReview_FullMethodName            = "/api.v1.ProductReviewsService/EditReview"
	ProductReviewsService_DeleteReview_FullMethodName          = "/api.v1.ProductReviewsService/DeleteReview"
)

// ProductReviewsServiceClient is the client API for ProductReviewsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductReviewsServiceClient interface {
	// CreateProduct allows to add a new Product resource to the inventory.
	// Response will contain Product resource with ID assigned internally by the system.
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error)
	// GetProduct allows to retrieve Product resource by specified ID.
	GetProductByID(ctx context.Context, in *GetProductByIDRequest, opts ...grpc.CallOption) (*GetProductByIDResponse, error)
	// EditProduct allows to update Product resource in a PATCH fashion.
	// Response contains Product resource reflecting recent changes.
	EditProduct(ctx context.Context, in *EditProductRequest, opts ...grpc.CallOption) (*EditProductResponse, error)
	// DeleteProduct allows to remove Product resource from the inventory.
	// In order to do so, you should remember ID assigned internally by the system.
	DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListProducts allows to retrieve all Product resources from the inventory.
	ListProducts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListProductsResponse, error)
	// CreateReview allows to add a new Review resource to the inventory.
	// Response will contain Product resource with ID assigned internally by the system.
	CreateReview(ctx context.Context, in *CreateReviewRequest, opts ...grpc.CallOption) (*CreateReviewResponse, error)
	// GetReviewsByProductID allows to retrieve Review resource by specified Product ID.
	GetReviewsByProductID(ctx context.Context, in *GetReviewsByProductIDRequest, opts ...grpc.CallOption) (*GetReviewsByProductIDResponse, error)
	// EditReview allows to update Review resource in a PATCH fashion.
	// Response contains Review resource reflecting recent changes.
	EditReview(ctx context.Context, in *EditReviewRequest, opts ...grpc.CallOption) (*EditReviewResponse, error)
	// DeleteReview allows to remove Review resource from the inventory.
	// In order to do so, you should remember ID assigned internally by the system.
	DeleteReview(ctx context.Context, in *DeleteReviewRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type productReviewsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductReviewsServiceClient(cc grpc.ClientConnInterface) ProductReviewsServiceClient {
	return &productReviewsServiceClient{cc}
}

func (c *productReviewsServiceClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProductResponse)
	err := c.cc.Invoke(ctx, ProductReviewsService_CreateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productReviewsServiceClient) GetProductByID(ctx context.Context, in *GetProductByIDRequest, opts ...grpc.CallOption) (*GetProductByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductByIDResponse)
	err := c.cc.Invoke(ctx, ProductReviewsService_GetProductByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productReviewsServiceClient) EditProduct(ctx context.Context, in *EditProductRequest, opts ...grpc.CallOption) (*EditProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditProductResponse)
	err := c.cc.Invoke(ctx, ProductReviewsService_EditProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productReviewsServiceClient) DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ProductReviewsService_DeleteProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productReviewsServiceClient) ListProducts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductsResponse)
	err := c.cc.Invoke(ctx, ProductReviewsService_ListProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productReviewsServiceClient) CreateReview(ctx context.Context, in *CreateReviewRequest, opts ...grpc.CallOption) (*CreateReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReviewResponse)
	err := c.cc.Invoke(ctx, ProductReviewsService_CreateReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productReviewsServiceClient) GetReviewsByProductID(ctx context.Context, in *GetReviewsByProductIDRequest, opts ...grpc.CallOption) (*GetReviewsByProductIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReviewsByProductIDResponse)
	err := c.cc.Invoke(ctx, ProductReviewsService_GetReviewsByProductID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productReviewsServiceClient) EditReview(ctx context.Context, in *EditReviewRequest, opts ...grpc.CallOption) (*EditReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditReviewResponse)
	err := c.cc.Invoke(ctx, ProductReviewsService_EditReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productReviewsServiceClient) DeleteReview(ctx context.Context, in *DeleteReviewRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ProductReviewsService_DeleteReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductReviewsServiceServer is the server API for ProductReviewsService service.
// All implementations should embed UnimplementedProductReviewsServiceServer
// for forward compatibility.
type ProductReviewsServiceServer interface {
	// CreateProduct allows to add a new Product resource to the inventory.
	// Response will contain Product resource with ID assigned internally by the system.
	CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error)
	// GetProduct allows to retrieve Product resource by specified ID.
	GetProductByID(context.Context, *GetProductByIDRequest) (*GetProductByIDResponse, error)
	// EditProduct allows to update Product resource in a PATCH fashion.
	// Response contains Product resource reflecting recent changes.
	EditProduct(context.Context, *EditProductRequest) (*EditProductResponse, error)
	// DeleteProduct allows to remove Product resource from the inventory.
	// In order to do so, you should remember ID assigned internally by the system.
	DeleteProduct(context.Context, *DeleteProductRequest) (*emptypb.Empty, error)
	// ListProducts allows to retrieve all Product resources from the inventory.
	ListProducts(context.Context, *emptypb.Empty) (*ListProductsResponse, error)
	// CreateReview allows to add a new Review resource to the inventory.
	// Response will contain Product resource with ID assigned internally by the system.
	CreateReview(context.Context, *CreateReviewRequest) (*CreateReviewResponse, error)
	// GetReviewsByProductID allows to retrieve Review resource by specified Product ID.
	GetReviewsByProductID(context.Context, *GetReviewsByProductIDRequest) (*GetReviewsByProductIDResponse, error)
	// EditReview allows to update Review resource in a PATCH fashion.
	// Response contains Review resource reflecting recent changes.
	EditReview(context.Context, *EditReviewRequest) (*EditReviewResponse, error)
	// DeleteReview allows to remove Review resource from the inventory.
	// In order to do so, you should remember ID assigned internally by the system.
	DeleteReview(context.Context, *DeleteReviewRequest) (*emptypb.Empty, error)
}

// UnimplementedProductReviewsServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductReviewsServiceServer struct{}

func (UnimplementedProductReviewsServiceServer) CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedProductReviewsServiceServer) GetProductByID(context.Context, *GetProductByIDRequest) (*GetProductByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductByID not implemented")
}
func (UnimplementedProductReviewsServiceServer) EditProduct(context.Context, *EditProductRequest) (*EditProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EditProduct not implemented")
}
func (UnimplementedProductReviewsServiceServer) DeleteProduct(context.Context, *DeleteProductRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (UnimplementedProductReviewsServiceServer) ListProducts(context.Context, *emptypb.Empty) (*ListProductsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProducts not implemented")
}
func (UnimplementedProductReviewsServiceServer) CreateReview(context.Context, *CreateReviewRequest) (*CreateReviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateReview not implemented")
}
func (UnimplementedProductReviewsServiceServer) GetReviewsByProductID(context.Context, *GetReviewsByProductIDRequest) (*GetReviewsByProductIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReviewsByProductID not implemented")
}
func (UnimplementedProductReviewsServiceServer) EditReview(context.Context, *EditReviewRequest) (*EditReviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EditReview not implemented")
}
func (UnimplementedProductReviewsServiceServer) DeleteReview(context.Context, *DeleteReviewRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteReview not implemented")
}
func (UnimplementedProductReviewsServiceServer) testEmbeddedByValue() {}

// UnsafeProductReviewsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductReviewsServiceServer will
// result in compilation errors.
type UnsafeProductReviewsServiceServer interface {
	mustEmbedUnimplementedProductReviewsServiceServer()
}

func RegisterProductReviewsServiceServer(s grpc.ServiceRegistrar, srv ProductReviewsServiceServer) {
	// If the following call panics, it indicates UnimplementedProductReviewsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductReviewsService_ServiceDesc, srv)
}

func _ProductReviewsService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductReviewsServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductReviewsService_CreateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductReviewsServiceServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductReviewsService_GetProductByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductReviewsServiceServer).GetProductByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductReviewsService_GetProductByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductReviewsServiceServer).GetProductByID(ctx, req.(*GetProductByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductReviewsService_EditProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductReviewsServiceServer).EditProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductReviewsService_EditProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductReviewsServiceServer).EditProduct(ctx, req.(*EditProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductReviewsService_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductReviewsServiceServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductReviewsService_DeleteProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductReviewsServiceServer).DeleteProduct(ctx, req.(*DeleteProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductReviewsService_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductReviewsServiceServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductReviewsService_ListProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductReviewsServiceServer).ListProducts(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductReviewsService_CreateReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductReviewsServiceServer).CreateReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductReviewsService_CreateReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductReviewsServiceServer).CreateReview(ctx, req.(*CreateReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductReviewsService_GetReviewsByProductID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReviewsByProductIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductReviewsServiceServer).GetReviewsByProductID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductReviewsService_GetReviewsByProductID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductReviewsServiceServer).GetReviewsByProductID(ctx, req.(*GetReviewsByProductIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductReviewsService_EditReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductReviewsServiceServer).EditReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductReviewsService_EditReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductReviewsServiceServer).EditReview(ctx, req.(*EditReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductReviewsService_DeleteReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductReviewsServiceServer).DeleteReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductReviewsService_DeleteReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductReviewsServiceServer).DeleteReview(ctx, req.(*DeleteReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductReviewsService_ServiceDesc is the grpc.ServiceDesc for ProductReviewsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductReviewsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.ProductReviewsService",
	HandlerType: (*ProductReviewsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProduct",
			Handler:    _ProductReviewsService_CreateProduct_Handler,
		},
		{
			MethodName: "GetProductByID",
			Handler:    _ProductReviewsService_GetProductByID_Handler,
		},
		{
			MethodName: "EditProduct",
			Handler:    _ProductReviewsService_EditProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _ProductReviewsService_DeleteProduct_Handler,
		},
		{
			MethodName: "ListProducts",
			Handler:    _ProductReviewsService_ListProducts_Handler,
		},
		{
			MethodName: "CreateReview",
			Handler:    _ProductReviewsService_CreateReview_Handler,
		},
		{
			MethodName: "GetReviewsByProductID",
			Handler:    _ProductReviewsService_GetReviewsByProductID_Handler,
		},
		{
			MethodName: "EditReview",
			Handler:    _ProductReviewsService_EditReview_Handler,
		},
		{
			MethodName: "DeleteReview",
			Handler:    _ProductReviewsService_DeleteReview_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/product_reviews.proto",
}
