// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/v1/product-reviews.proto

package apiv1

import (
	_ "entgo.io/contrib/entproto/cmd/protoc-gen-ent/options/ent"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Set of messages for Product resource manipulation
type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_api_v1_product_reviews_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_reviews_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_product_reviews_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProductRequest) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_api_v1_product_reviews_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_reviews_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_product_reviews_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type GetProductByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductByIDRequest) Reset() {
	*x = GetProductByIDRequest{}
	mi := &file_api_v1_product_reviews_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductByIDRequest) ProtoMessage() {}

func (x *GetProductByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_reviews_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductByIDRequest.ProtoReflect.Descriptor instead.
func (*GetProductByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_product_reviews_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProductByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductByIDResponse) Reset() {
	*x = GetProductByIDResponse{}
	mi := &file_api_v1_product_reviews_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductByIDResponse) ProtoMessage() {}

func (x *GetProductByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_reviews_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductByIDResponse.ProtoReflect.Descriptor instead.
func (*GetProductByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_product_reviews_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductByIDResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type EditProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditProductRequest) Reset() {
	*x = EditProductRequest{}
	mi := &file_api_v1_product_reviews_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditProductRequest) ProtoMessage() {}

func (x *EditProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_reviews_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditProductRequest.ProtoReflect.Descriptor instead.
func (*EditProductRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_product_reviews_proto_rawDescGZIP(), []int{4}
}

func (x *EditProductRequest) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type EditProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditProductResponse) Reset() {
	*x = EditProductResponse{}
	mi := &file_api_v1_product_reviews_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditProductResponse) ProtoMessage() {}

func (x *EditProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_reviews_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditProductResponse.ProtoReflect.Descriptor instead.
func (*EditProductResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_product_reviews_proto_rawDescGZIP(), []int{5}
}

func (x *EditProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_api_v1_product_reviews_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_reviews_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_product_reviews_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_api_v1_product_reviews_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_reviews_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_product_reviews_proto_rawDescGZIP(), []int{7}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

// Set of messages for Review resource manipulation
type CreateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *Review                `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewRequest) Reset() {
	*x = CreateReviewRequest{}
	mi := &file_api_v1_product_reviews_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewRequest) ProtoMessage() {}

func (x *CreateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_reviews_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewRequest.ProtoReflect.Descriptor instead.
func (*CreateReviewRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_product_reviews_proto_rawDescGZIP(), []int{8}
}

func (x *CreateReviewRequest) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

type CreateReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *Review                `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewResponse) Reset() {
	*x = CreateReviewResponse{}
	mi := &file_api_v1_product_reviews_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewResponse) ProtoMessage() {}

func (x *CreateReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_reviews_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewResponse.ProtoReflect.Descriptor instead.
func (*CreateReviewResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_product_reviews_proto_rawDescGZIP(), []int{9}
}

func (x *CreateReviewResponse) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

type EditReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *Review                `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditReviewRequest) Reset() {
	*x = EditReviewRequest{}
	mi := &file_api_v1_product_reviews_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditReviewRequest) ProtoMessage() {}

func (x *EditReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_reviews_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditReviewRequest.ProtoReflect.Descriptor instead.
func (*EditReviewRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_product_reviews_proto_rawDescGZIP(), []int{10}
}

func (x *EditReviewRequest) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

type EditReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *Review                `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditReviewResponse) Reset() {
	*x = EditReviewResponse{}
	mi := &file_api_v1_product_reviews_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditReviewResponse) ProtoMessage() {}

func (x *EditReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_reviews_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditReviewResponse.ProtoReflect.Descriptor instead.
func (*EditReviewResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_product_reviews_proto_rawDescGZIP(), []int{11}
}

func (x *EditReviewResponse) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

type DeleteReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReviewRequest) Reset() {
	*x = DeleteReviewRequest{}
	mi := &file_api_v1_product_reviews_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReviewRequest) ProtoMessage() {}

func (x *DeleteReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_reviews_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReviewRequest.ProtoReflect.Descriptor instead.
func (*DeleteReviewRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_product_reviews_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteReviewRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetReviewsByProductIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // this is a Product resource ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewsByProductIDRequest) Reset() {
	*x = GetReviewsByProductIDRequest{}
	mi := &file_api_v1_product_reviews_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewsByProductIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewsByProductIDRequest) ProtoMessage() {}

func (x *GetReviewsByProductIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_reviews_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewsByProductIDRequest.ProtoReflect.Descriptor instead.
func (*GetReviewsByProductIDRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_product_reviews_proto_rawDescGZIP(), []int{13}
}

func (x *GetReviewsByProductIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetReviewsByProductIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*Review              `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewsByProductIDResponse) Reset() {
	*x = GetReviewsByProductIDResponse{}
	mi := &file_api_v1_product_reviews_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewsByProductIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewsByProductIDResponse) ProtoMessage() {}

func (x *GetReviewsByProductIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_reviews_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewsByProductIDResponse.ProtoReflect.Descriptor instead.
func (*GetReviewsByProductIDResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_product_reviews_proto_rawDescGZIP(), []int{14}
}

func (x *GetReviewsByProductIDResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

// Modelling DB resources below.
// Product resource definition.
type Product struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the product resource internally assigned by the controller.
	Id            string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         string    `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"` // this is to avoid floating point number precision issues
	Reviews       []*Review `protobuf:"bytes,5,rep,name=reviews,proto3" json:"reviews,omitempty"`
	AverageRating string    `protobuf:"bytes,6,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"` // might not be part of the product
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_api_v1_product_reviews_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_reviews_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_api_v1_product_reviews_proto_rawDescGZIP(), []int{15}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Product) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

func (x *Product) GetAverageRating() string {
	if x != nil {
		return x.AverageRating
	}
	return ""
}

// Review resource definition.
type Review struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the review resource internally assigned by the controller.
	Id            string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	ReviewText    string   `protobuf:"bytes,4,opt,name=review_text,json=reviewText,proto3" json:"review_text,omitempty"`
	Rating        int32    `protobuf:"varint,5,opt,name=rating,proto3" json:"rating,omitempty"`
	Product       *Product `protobuf:"bytes,10,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_api_v1_product_reviews_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_product_reviews_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_api_v1_product_reviews_proto_rawDescGZIP(), []int{16}
}

func (x *Review) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Review) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Review) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Review) GetReviewText() string {
	if x != nil {
		return x.ReviewText
	}
	return ""
}

func (x *Review) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Review) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

var File_api_v1_product_reviews_proto protoreflect.FileDescriptor

const file_api_v1_product_reviews_proto_rawDesc = "" +
	"\n" +
	"\x1capi/v1/product-reviews.proto\x12\x06api.v1\x1a\x15api/v1/ent/opts.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"A\n" +
	"\x14CreateProductRequest\x12)\n" +
	"\aproduct\x18\x01 \x01(\v2\x0f.api.v1.ProductR\aproduct\"B\n" +
	"\x15CreateProductResponse\x12)\n" +
	"\aproduct\x18\x01 \x01(\v2\x0f.api.v1.ProductR\aproduct\"'\n" +
	"\x15GetProductByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x16GetProductByIDResponse\x12)\n" +
	"\aproduct\x18\x01 \x01(\v2\x0f.api.v1.ProductR\aproduct\"?\n" +
	"\x12EditProductRequest\x12)\n" +
	"\aproduct\x18\x01 \x01(\v2\x0f.api.v1.ProductR\aproduct\"@\n" +
	"\x13EditProductResponse\x12)\n" +
	"\aproduct\x18\x01 \x01(\v2\x0f.api.v1.ProductR\aproduct\"&\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x14ListProductsResponse\x12+\n" +
	"\bproducts\x18\x01 \x03(\v2\x0f.api.v1.ProductR\bproducts\"=\n" +
	"\x13CreateReviewRequest\x12&\n" +
	"\x06review\x18\x01 \x01(\v2\x0e.api.v1.ReviewR\x06review\">\n" +
	"\x14CreateReviewResponse\x12&\n" +
	"\x06review\x18\x01 \x01(\v2\x0e.api.v1.ReviewR\x06review\";\n" +
	"\x11EditReviewRequest\x12&\n" +
	"\x06review\x18\x01 \x01(\v2\x0e.api.v1.ReviewR\x06review\"<\n" +
	"\x12EditReviewResponse\x12&\n" +
	"\x06review\x18\x01 \x01(\v2\x0e.api.v1.ReviewR\x06review\"%\n" +
	"\x13DeleteReviewRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x1cGetReviewsByProductIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"I\n" +
	"\x1dGetReviewsByProductIDResponse\x12(\n" +
	"\areviews\x18\x01 \x03(\v2\x0e.api.v1.ReviewR\areviews\"\xc4\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\tR\x05price\x12.\n" +
	"\areviews\x18\x05 \x03(\v2\x0e.api.v1.ReviewB\x04¦I\x00R\areviews\x12%\n" +
	"\x0eaverage_rating\x18\x06 \x01(\tR\raverageRating:\x06\xba\xa6I\x02\b\x01\"\xd1\x01\n" +
	"\x06Review\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x1f\n" +
	"\vreview_text\x18\x04 \x01(\tR\n" +
	"reviewText\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x05R\x06rating\x12:\n" +
	"\aproduct\x18\n" +
	" \x01(\v2\x0f.api.v1.ProductB\x0f¦I\v\b\x01\x12\areviewsR\aproduct:\x06\xba\xa6I\x02\b\x012\xcf\a\n" +
	"\x17DeviceMonitoringService\x12k\n" +
	"\rCreateProduct\x12\x1c.api.v1.CreateProductRequest\x1a\x1d.api.v1.CreateProductResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/product/create\x12i\n" +
	"\n" +
	"GetProduct\x12\x1d.api.v1.GetProductByIDRequest\x1a\x1e.api.v1.GetProductByIDResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/product/get/{id}\x12c\n" +
	"\vEditProduct\x12\x1a.api.v1.EditProductRequest\x1a\x1b.api.v1.EditProductResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*2\x10/v1/product/edit\x12b\n" +
	"\rDeleteProduct\x12\x1c.api.v1.DeleteProductRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01**\x10/v1/product/{id}\x12]\n" +
	"\fListProducts\x12\x16.google.protobuf.Empty\x1a\x1c.api.v1.ListProductsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/product/all\x12g\n" +
	"\fCreateReview\x12\x1b.api.v1.CreateReviewRequest\x1a\x1c.api.v1.CreateReviewResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/review/create\x12\x88\x01\n" +
	"\x14GetReviewByProductID\x12$.api.v1.GetReviewsByProductIDRequest\x1a%.api.v1.GetReviewsByProductIDResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/review/get/product/{id}\x12_\n" +
	"\n" +
	"EditReview\x12\x19.api.v1.EditReviewRequest\x1a\x1a.api.v1.EditReviewResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*2\x0f/v1/review/edit\x12_\n" +
	"\fDeleteReview\x12\x1b.api.v1.DeleteReviewRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01**\x0f/v1/review/{id}B<Z:github.com/eroshiva/cloudtalk/api/v1/product-reviews;apiv1b\x06proto3"

var (
	file_api_v1_product_reviews_proto_rawDescOnce sync.Once
	file_api_v1_product_reviews_proto_rawDescData []byte
)

func file_api_v1_product_reviews_proto_rawDescGZIP() []byte {
	file_api_v1_product_reviews_proto_rawDescOnce.Do(func() {
		file_api_v1_product_reviews_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_product_reviews_proto_rawDesc), len(file_api_v1_product_reviews_proto_rawDesc)))
	})
	return file_api_v1_product_reviews_proto_rawDescData
}

var file_api_v1_product_reviews_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_v1_product_reviews_proto_goTypes = []any{
	(*CreateProductRequest)(nil),          // 0: api.v1.CreateProductRequest
	(*CreateProductResponse)(nil),         // 1: api.v1.CreateProductResponse
	(*GetProductByIDRequest)(nil),         // 2: api.v1.GetProductByIDRequest
	(*GetProductByIDResponse)(nil),        // 3: api.v1.GetProductByIDResponse
	(*EditProductRequest)(nil),            // 4: api.v1.EditProductRequest
	(*EditProductResponse)(nil),           // 5: api.v1.EditProductResponse
	(*DeleteProductRequest)(nil),          // 6: api.v1.DeleteProductRequest
	(*ListProductsResponse)(nil),          // 7: api.v1.ListProductsResponse
	(*CreateReviewRequest)(nil),           // 8: api.v1.CreateReviewRequest
	(*CreateReviewResponse)(nil),          // 9: api.v1.CreateReviewResponse
	(*EditReviewRequest)(nil),             // 10: api.v1.EditReviewRequest
	(*EditReviewResponse)(nil),            // 11: api.v1.EditReviewResponse
	(*DeleteReviewRequest)(nil),           // 12: api.v1.DeleteReviewRequest
	(*GetReviewsByProductIDRequest)(nil),  // 13: api.v1.GetReviewsByProductIDRequest
	(*GetReviewsByProductIDResponse)(nil), // 14: api.v1.GetReviewsByProductIDResponse
	(*Product)(nil),                       // 15: api.v1.Product
	(*Review)(nil),                        // 16: api.v1.Review
	(*emptypb.Empty)(nil),                 // 17: google.protobuf.Empty
}
var file_api_v1_product_reviews_proto_depIdxs = []int32{
	15, // 0: api.v1.CreateProductRequest.product:type_name -> api.v1.Product
	15, // 1: api.v1.CreateProductResponse.product:type_name -> api.v1.Product
	15, // 2: api.v1.GetProductByIDResponse.product:type_name -> api.v1.Product
	15, // 3: api.v1.EditProductRequest.product:type_name -> api.v1.Product
	15, // 4: api.v1.EditProductResponse.product:type_name -> api.v1.Product
	15, // 5: api.v1.ListProductsResponse.products:type_name -> api.v1.Product
	16, // 6: api.v1.CreateReviewRequest.review:type_name -> api.v1.Review
	16, // 7: api.v1.CreateReviewResponse.review:type_name -> api.v1.Review
	16, // 8: api.v1.EditReviewRequest.review:type_name -> api.v1.Review
	16, // 9: api.v1.EditReviewResponse.review:type_name -> api.v1.Review
	16, // 10: api.v1.GetReviewsByProductIDResponse.reviews:type_name -> api.v1.Review
	16, // 11: api.v1.Product.reviews:type_name -> api.v1.Review
	15, // 12: api.v1.Review.product:type_name -> api.v1.Product
	0,  // 13: api.v1.DeviceMonitoringService.CreateProduct:input_type -> api.v1.CreateProductRequest
	2,  // 14: api.v1.DeviceMonitoringService.GetProduct:input_type -> api.v1.GetProductByIDRequest
	4,  // 15: api.v1.DeviceMonitoringService.EditProduct:input_type -> api.v1.EditProductRequest
	6,  // 16: api.v1.DeviceMonitoringService.DeleteProduct:input_type -> api.v1.DeleteProductRequest
	17, // 17: api.v1.DeviceMonitoringService.ListProducts:input_type -> google.protobuf.Empty
	8,  // 18: api.v1.DeviceMonitoringService.CreateReview:input_type -> api.v1.CreateReviewRequest
	13, // 19: api.v1.DeviceMonitoringService.GetReviewByProductID:input_type -> api.v1.GetReviewsByProductIDRequest
	10, // 20: api.v1.DeviceMonitoringService.EditReview:input_type -> api.v1.EditReviewRequest
	12, // 21: api.v1.DeviceMonitoringService.DeleteReview:input_type -> api.v1.DeleteReviewRequest
	1,  // 22: api.v1.DeviceMonitoringService.CreateProduct:output_type -> api.v1.CreateProductResponse
	3,  // 23: api.v1.DeviceMonitoringService.GetProduct:output_type -> api.v1.GetProductByIDResponse
	5,  // 24: api.v1.DeviceMonitoringService.EditProduct:output_type -> api.v1.EditProductResponse
	17, // 25: api.v1.DeviceMonitoringService.DeleteProduct:output_type -> google.protobuf.Empty
	7,  // 26: api.v1.DeviceMonitoringService.ListProducts:output_type -> api.v1.ListProductsResponse
	9,  // 27: api.v1.DeviceMonitoringService.CreateReview:output_type -> api.v1.CreateReviewResponse
	14, // 28: api.v1.DeviceMonitoringService.GetReviewByProductID:output_type -> api.v1.GetReviewsByProductIDResponse
	11, // 29: api.v1.DeviceMonitoringService.EditReview:output_type -> api.v1.EditReviewResponse
	17, // 30: api.v1.DeviceMonitoringService.DeleteReview:output_type -> google.protobuf.Empty
	22, // [22:31] is the sub-list for method output_type
	13, // [13:22] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_v1_product_reviews_proto_init() }
func file_api_v1_product_reviews_proto_init() {
	if File_api_v1_product_reviews_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_product_reviews_proto_rawDesc), len(file_api_v1_product_reviews_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_product_reviews_proto_goTypes,
		DependencyIndexes: file_api_v1_product_reviews_proto_depIdxs,
		MessageInfos:      file_api_v1_product_reviews_proto_msgTypes,
	}.Build()
	File_api_v1_product_reviews_proto = out.File
	file_api_v1_product_reviews_proto_goTypes = nil
	file_api_v1_product_reviews_proto_depIdxs = nil
}
