// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: api/v1/product-reviews.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeviceMonitoringService_CreateProduct_FullMethodName        = "/api.v1.DeviceMonitoringService/CreateProduct"
	DeviceMonitoringService_GetProduct_FullMethodName           = "/api.v1.DeviceMonitoringService/GetProduct"
	DeviceMonitoringService_EditProduct_FullMethodName          = "/api.v1.DeviceMonitoringService/EditProduct"
	DeviceMonitoringService_DeleteProduct_FullMethodName        = "/api.v1.DeviceMonitoringService/DeleteProduct"
	DeviceMonitoringService_ListProducts_FullMethodName         = "/api.v1.DeviceMonitoringService/ListProducts"
	DeviceMonitoringService_CreateReview_FullMethodName         = "/api.v1.DeviceMonitoringService/CreateReview"
	DeviceMonitoringService_GetReviewByProductID_FullMethodName = "/api.v1.DeviceMonitoringService/GetReviewByProductID"
	DeviceMonitoringService_EditReview_FullMethodName           = "/api.v1.DeviceMonitoringService/EditReview"
	DeviceMonitoringService_DeleteReview_FullMethodName         = "/api.v1.DeviceMonitoringService/DeleteReview"
)

// DeviceMonitoringServiceClient is the client API for DeviceMonitoringService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceMonitoringServiceClient interface {
	// CreateProduct allows to add a new Product resource to the inventory.
	// Response will contain Product resource with ID assigned internally by the system.
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error)
	// GetProduct allows to retrieve Product resource by specified ID.
	GetProduct(ctx context.Context, in *GetProductByIDRequest, opts ...grpc.CallOption) (*GetProductByIDResponse, error)
	// EditProduct allows to update Product resource in a PATCH fashion.
	// Response contains Product resource reflecting recent changes.
	EditProduct(ctx context.Context, in *EditProductRequest, opts ...grpc.CallOption) (*EditProductResponse, error)
	// DeleteProduct allows to remove Product resource from the inventory.
	// In order to do so, you should remember ID assigned internally by the system.
	DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListProducts allows to retrieve all Product resources from the inventory.
	ListProducts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListProductsResponse, error)
	// CreateReview allows to add a new Review resource to the inventory.
	// Response will contain Product resource with ID assigned internally by the system.
	CreateReview(ctx context.Context, in *CreateReviewRequest, opts ...grpc.CallOption) (*CreateReviewResponse, error)
	// GetReviewByProductID allows to retrieve Review resource by specified Product ID.
	GetReviewByProductID(ctx context.Context, in *GetReviewsByProductIDRequest, opts ...grpc.CallOption) (*GetReviewsByProductIDResponse, error)
	// EditReview allows to update Review resource in a PATCH fashion.
	// Response contains Review resource reflecting recent changes.
	EditReview(ctx context.Context, in *EditReviewRequest, opts ...grpc.CallOption) (*EditReviewResponse, error)
	// DeleteReview allows to remove Review resource from the inventory.
	// In order to do so, you should remember ID assigned internally by the system.
	DeleteReview(ctx context.Context, in *DeleteReviewRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type deviceMonitoringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceMonitoringServiceClient(cc grpc.ClientConnInterface) DeviceMonitoringServiceClient {
	return &deviceMonitoringServiceClient{cc}
}

func (c *deviceMonitoringServiceClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProductResponse)
	err := c.cc.Invoke(ctx, DeviceMonitoringService_CreateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceMonitoringServiceClient) GetProduct(ctx context.Context, in *GetProductByIDRequest, opts ...grpc.CallOption) (*GetProductByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductByIDResponse)
	err := c.cc.Invoke(ctx, DeviceMonitoringService_GetProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceMonitoringServiceClient) EditProduct(ctx context.Context, in *EditProductRequest, opts ...grpc.CallOption) (*EditProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditProductResponse)
	err := c.cc.Invoke(ctx, DeviceMonitoringService_EditProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceMonitoringServiceClient) DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DeviceMonitoringService_DeleteProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceMonitoringServiceClient) ListProducts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductsResponse)
	err := c.cc.Invoke(ctx, DeviceMonitoringService_ListProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceMonitoringServiceClient) CreateReview(ctx context.Context, in *CreateReviewRequest, opts ...grpc.CallOption) (*CreateReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReviewResponse)
	err := c.cc.Invoke(ctx, DeviceMonitoringService_CreateReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceMonitoringServiceClient) GetReviewByProductID(ctx context.Context, in *GetReviewsByProductIDRequest, opts ...grpc.CallOption) (*GetReviewsByProductIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReviewsByProductIDResponse)
	err := c.cc.Invoke(ctx, DeviceMonitoringService_GetReviewByProductID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceMonitoringServiceClient) EditReview(ctx context.Context, in *EditReviewRequest, opts ...grpc.CallOption) (*EditReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditReviewResponse)
	err := c.cc.Invoke(ctx, DeviceMonitoringService_EditReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceMonitoringServiceClient) DeleteReview(ctx context.Context, in *DeleteReviewRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DeviceMonitoringService_DeleteReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceMonitoringServiceServer is the server API for DeviceMonitoringService service.
// All implementations should embed UnimplementedDeviceMonitoringServiceServer
// for forward compatibility.
type DeviceMonitoringServiceServer interface {
	// CreateProduct allows to add a new Product resource to the inventory.
	// Response will contain Product resource with ID assigned internally by the system.
	CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error)
	// GetProduct allows to retrieve Product resource by specified ID.
	GetProduct(context.Context, *GetProductByIDRequest) (*GetProductByIDResponse, error)
	// EditProduct allows to update Product resource in a PATCH fashion.
	// Response contains Product resource reflecting recent changes.
	EditProduct(context.Context, *EditProductRequest) (*EditProductResponse, error)
	// DeleteProduct allows to remove Product resource from the inventory.
	// In order to do so, you should remember ID assigned internally by the system.
	DeleteProduct(context.Context, *DeleteProductRequest) (*emptypb.Empty, error)
	// ListProducts allows to retrieve all Product resources from the inventory.
	ListProducts(context.Context, *emptypb.Empty) (*ListProductsResponse, error)
	// CreateReview allows to add a new Review resource to the inventory.
	// Response will contain Product resource with ID assigned internally by the system.
	CreateReview(context.Context, *CreateReviewRequest) (*CreateReviewResponse, error)
	// GetReviewByProductID allows to retrieve Review resource by specified Product ID.
	GetReviewByProductID(context.Context, *GetReviewsByProductIDRequest) (*GetReviewsByProductIDResponse, error)
	// EditReview allows to update Review resource in a PATCH fashion.
	// Response contains Review resource reflecting recent changes.
	EditReview(context.Context, *EditReviewRequest) (*EditReviewResponse, error)
	// DeleteReview allows to remove Review resource from the inventory.
	// In order to do so, you should remember ID assigned internally by the system.
	DeleteReview(context.Context, *DeleteReviewRequest) (*emptypb.Empty, error)
}

// UnimplementedDeviceMonitoringServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceMonitoringServiceServer struct{}

func (UnimplementedDeviceMonitoringServiceServer) CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedDeviceMonitoringServiceServer) GetProduct(context.Context, *GetProductByIDRequest) (*GetProductByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedDeviceMonitoringServiceServer) EditProduct(context.Context, *EditProductRequest) (*EditProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EditProduct not implemented")
}
func (UnimplementedDeviceMonitoringServiceServer) DeleteProduct(context.Context, *DeleteProductRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (UnimplementedDeviceMonitoringServiceServer) ListProducts(context.Context, *emptypb.Empty) (*ListProductsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProducts not implemented")
}
func (UnimplementedDeviceMonitoringServiceServer) CreateReview(context.Context, *CreateReviewRequest) (*CreateReviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateReview not implemented")
}
func (UnimplementedDeviceMonitoringServiceServer) GetReviewByProductID(context.Context, *GetReviewsByProductIDRequest) (*GetReviewsByProductIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReviewByProductID not implemented")
}
func (UnimplementedDeviceMonitoringServiceServer) EditReview(context.Context, *EditReviewRequest) (*EditReviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EditReview not implemented")
}
func (UnimplementedDeviceMonitoringServiceServer) DeleteReview(context.Context, *DeleteReviewRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteReview not implemented")
}
func (UnimplementedDeviceMonitoringServiceServer) testEmbeddedByValue() {}

// UnsafeDeviceMonitoringServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceMonitoringServiceServer will
// result in compilation errors.
type UnsafeDeviceMonitoringServiceServer interface {
	mustEmbedUnimplementedDeviceMonitoringServiceServer()
}

func RegisterDeviceMonitoringServiceServer(s grpc.ServiceRegistrar, srv DeviceMonitoringServiceServer) {
	// If the following call panics, it indicates UnimplementedDeviceMonitoringServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceMonitoringService_ServiceDesc, srv)
}

func _DeviceMonitoringService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceMonitoringServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceMonitoringService_CreateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceMonitoringServiceServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceMonitoringService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceMonitoringServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceMonitoringService_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceMonitoringServiceServer).GetProduct(ctx, req.(*GetProductByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceMonitoringService_EditProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceMonitoringServiceServer).EditProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceMonitoringService_EditProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceMonitoringServiceServer).EditProduct(ctx, req.(*EditProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceMonitoringService_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceMonitoringServiceServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceMonitoringService_DeleteProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceMonitoringServiceServer).DeleteProduct(ctx, req.(*DeleteProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceMonitoringService_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceMonitoringServiceServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceMonitoringService_ListProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceMonitoringServiceServer).ListProducts(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceMonitoringService_CreateReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceMonitoringServiceServer).CreateReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceMonitoringService_CreateReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceMonitoringServiceServer).CreateReview(ctx, req.(*CreateReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceMonitoringService_GetReviewByProductID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReviewsByProductIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceMonitoringServiceServer).GetReviewByProductID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceMonitoringService_GetReviewByProductID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceMonitoringServiceServer).GetReviewByProductID(ctx, req.(*GetReviewsByProductIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceMonitoringService_EditReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceMonitoringServiceServer).EditReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceMonitoringService_EditReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceMonitoringServiceServer).EditReview(ctx, req.(*EditReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceMonitoringService_DeleteReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceMonitoringServiceServer).DeleteReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceMonitoringService_DeleteReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceMonitoringServiceServer).DeleteReview(ctx, req.(*DeleteReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceMonitoringService_ServiceDesc is the grpc.ServiceDesc for DeviceMonitoringService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceMonitoringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.DeviceMonitoringService",
	HandlerType: (*DeviceMonitoringServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProduct",
			Handler:    _DeviceMonitoringService_CreateProduct_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _DeviceMonitoringService_GetProduct_Handler,
		},
		{
			MethodName: "EditProduct",
			Handler:    _DeviceMonitoringService_EditProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _DeviceMonitoringService_DeleteProduct_Handler,
		},
		{
			MethodName: "ListProducts",
			Handler:    _DeviceMonitoringService_ListProducts_Handler,
		},
		{
			MethodName: "CreateReview",
			Handler:    _DeviceMonitoringService_CreateReview_Handler,
		},
		{
			MethodName: "GetReviewByProductID",
			Handler:    _DeviceMonitoringService_GetReviewByProductID_Handler,
		},
		{
			MethodName: "EditReview",
			Handler:    _DeviceMonitoringService_EditReview_Handler,
		},
		{
			MethodName: "DeleteReview",
			Handler:    _DeviceMonitoringService_DeleteReview_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/product-reviews.proto",
}
