// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/eroshiva/cloudtalk/internal/ent/predicate"
	"github.com/eroshiva/cloudtalk/internal/ent/product"
	"github.com/eroshiva/cloudtalk/internal/ent/review"
)

// ReviewUpdate is the builder for updating Review entities.
type ReviewUpdate struct {
	config
	hooks    []Hook
	mutation *ReviewMutation
}

// Where appends a list predicates to the ReviewUpdate builder.
func (_u *ReviewUpdate) Where(ps ...predicate.Review) *ReviewUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetFirstName sets the "first_name" field.
func (_u *ReviewUpdate) SetFirstName(v string) *ReviewUpdate {
	_u.mutation.SetFirstName(v)
	return _u
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_u *ReviewUpdate) SetNillableFirstName(v *string) *ReviewUpdate {
	if v != nil {
		_u.SetFirstName(*v)
	}
	return _u
}

// SetLastName sets the "last_name" field.
func (_u *ReviewUpdate) SetLastName(v string) *ReviewUpdate {
	_u.mutation.SetLastName(v)
	return _u
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_u *ReviewUpdate) SetNillableLastName(v *string) *ReviewUpdate {
	if v != nil {
		_u.SetLastName(*v)
	}
	return _u
}

// SetReviewText sets the "review_text" field.
func (_u *ReviewUpdate) SetReviewText(v string) *ReviewUpdate {
	_u.mutation.SetReviewText(v)
	return _u
}

// SetNillableReviewText sets the "review_text" field if the given value is not nil.
func (_u *ReviewUpdate) SetNillableReviewText(v *string) *ReviewUpdate {
	if v != nil {
		_u.SetReviewText(*v)
	}
	return _u
}

// SetRating sets the "rating" field.
func (_u *ReviewUpdate) SetRating(v int32) *ReviewUpdate {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *ReviewUpdate) SetNillableRating(v *int32) *ReviewUpdate {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *ReviewUpdate) AddRating(v int32) *ReviewUpdate {
	_u.mutation.AddRating(v)
	return _u
}

// SetProductID sets the "product" edge to the Product entity by ID.
func (_u *ReviewUpdate) SetProductID(id string) *ReviewUpdate {
	_u.mutation.SetProductID(id)
	return _u
}

// SetNillableProductID sets the "product" edge to the Product entity by ID if the given value is not nil.
func (_u *ReviewUpdate) SetNillableProductID(id *string) *ReviewUpdate {
	if id != nil {
		_u = _u.SetProductID(*id)
	}
	return _u
}

// SetProduct sets the "product" edge to the Product entity.
func (_u *ReviewUpdate) SetProduct(v *Product) *ReviewUpdate {
	return _u.SetProductID(v.ID)
}

// Mutation returns the ReviewMutation object of the builder.
func (_u *ReviewUpdate) Mutation() *ReviewMutation {
	return _u.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (_u *ReviewUpdate) ClearProduct() *ReviewUpdate {
	_u.mutation.ClearProduct()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReviewUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReviewUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReviewUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReviewUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ReviewUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(review.Table, review.Columns, sqlgraph.NewFieldSpec(review.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FirstName(); ok {
		_spec.SetField(review.FieldFirstName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastName(); ok {
		_spec.SetField(review.FieldLastName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReviewText(); ok {
		_spec.SetField(review.FieldReviewText, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(review.FieldRating, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(review.FieldRating, field.TypeInt32, value)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.ProductTable,
			Columns: []string{review.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.ProductTable,
			Columns: []string{review.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{review.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReviewUpdateOne is the builder for updating a single Review entity.
type ReviewUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReviewMutation
}

// SetFirstName sets the "first_name" field.
func (_u *ReviewUpdateOne) SetFirstName(v string) *ReviewUpdateOne {
	_u.mutation.SetFirstName(v)
	return _u
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_u *ReviewUpdateOne) SetNillableFirstName(v *string) *ReviewUpdateOne {
	if v != nil {
		_u.SetFirstName(*v)
	}
	return _u
}

// SetLastName sets the "last_name" field.
func (_u *ReviewUpdateOne) SetLastName(v string) *ReviewUpdateOne {
	_u.mutation.SetLastName(v)
	return _u
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_u *ReviewUpdateOne) SetNillableLastName(v *string) *ReviewUpdateOne {
	if v != nil {
		_u.SetLastName(*v)
	}
	return _u
}

// SetReviewText sets the "review_text" field.
func (_u *ReviewUpdateOne) SetReviewText(v string) *ReviewUpdateOne {
	_u.mutation.SetReviewText(v)
	return _u
}

// SetNillableReviewText sets the "review_text" field if the given value is not nil.
func (_u *ReviewUpdateOne) SetNillableReviewText(v *string) *ReviewUpdateOne {
	if v != nil {
		_u.SetReviewText(*v)
	}
	return _u
}

// SetRating sets the "rating" field.
func (_u *ReviewUpdateOne) SetRating(v int32) *ReviewUpdateOne {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *ReviewUpdateOne) SetNillableRating(v *int32) *ReviewUpdateOne {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *ReviewUpdateOne) AddRating(v int32) *ReviewUpdateOne {
	_u.mutation.AddRating(v)
	return _u
}

// SetProductID sets the "product" edge to the Product entity by ID.
func (_u *ReviewUpdateOne) SetProductID(id string) *ReviewUpdateOne {
	_u.mutation.SetProductID(id)
	return _u
}

// SetNillableProductID sets the "product" edge to the Product entity by ID if the given value is not nil.
func (_u *ReviewUpdateOne) SetNillableProductID(id *string) *ReviewUpdateOne {
	if id != nil {
		_u = _u.SetProductID(*id)
	}
	return _u
}

// SetProduct sets the "product" edge to the Product entity.
func (_u *ReviewUpdateOne) SetProduct(v *Product) *ReviewUpdateOne {
	return _u.SetProductID(v.ID)
}

// Mutation returns the ReviewMutation object of the builder.
func (_u *ReviewUpdateOne) Mutation() *ReviewMutation {
	return _u.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (_u *ReviewUpdateOne) ClearProduct() *ReviewUpdateOne {
	_u.mutation.ClearProduct()
	return _u
}

// Where appends a list predicates to the ReviewUpdate builder.
func (_u *ReviewUpdateOne) Where(ps ...predicate.Review) *ReviewUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReviewUpdateOne) Select(field string, fields ...string) *ReviewUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Review entity.
func (_u *ReviewUpdateOne) Save(ctx context.Context) (*Review, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReviewUpdateOne) SaveX(ctx context.Context) *Review {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReviewUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReviewUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ReviewUpdateOne) sqlSave(ctx context.Context) (_node *Review, err error) {
	_spec := sqlgraph.NewUpdateSpec(review.Table, review.Columns, sqlgraph.NewFieldSpec(review.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Review.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, review.FieldID)
		for _, f := range fields {
			if !review.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != review.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FirstName(); ok {
		_spec.SetField(review.FieldFirstName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastName(); ok {
		_spec.SetField(review.FieldLastName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReviewText(); ok {
		_spec.SetField(review.FieldReviewText, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(review.FieldRating, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(review.FieldRating, field.TypeInt32, value)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.ProductTable,
			Columns: []string{review.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.ProductTable,
			Columns: []string{review.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Review{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{review.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
