// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/eroshiva/cloudtalk/internal/ent/predicate"
	"github.com/eroshiva/cloudtalk/internal/ent/product"
	"github.com/eroshiva/cloudtalk/internal/ent/review"
)

// ReviewUpdate is the builder for updating Review entities.
type ReviewUpdate struct {
	config
	hooks    []Hook
	mutation *ReviewMutation
}

// Where appends a list predicates to the ReviewUpdate builder.
func (ru *ReviewUpdate) Where(ps ...predicate.Review) *ReviewUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetFirstName sets the "first_name" field.
func (ru *ReviewUpdate) SetFirstName(s string) *ReviewUpdate {
	ru.mutation.SetFirstName(s)
	return ru
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (ru *ReviewUpdate) SetNillableFirstName(s *string) *ReviewUpdate {
	if s != nil {
		ru.SetFirstName(*s)
	}
	return ru
}

// SetLastName sets the "last_name" field.
func (ru *ReviewUpdate) SetLastName(s string) *ReviewUpdate {
	ru.mutation.SetLastName(s)
	return ru
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (ru *ReviewUpdate) SetNillableLastName(s *string) *ReviewUpdate {
	if s != nil {
		ru.SetLastName(*s)
	}
	return ru
}

// SetReviewText sets the "review_text" field.
func (ru *ReviewUpdate) SetReviewText(s string) *ReviewUpdate {
	ru.mutation.SetReviewText(s)
	return ru
}

// SetNillableReviewText sets the "review_text" field if the given value is not nil.
func (ru *ReviewUpdate) SetNillableReviewText(s *string) *ReviewUpdate {
	if s != nil {
		ru.SetReviewText(*s)
	}
	return ru
}

// SetRating sets the "rating" field.
func (ru *ReviewUpdate) SetRating(i int32) *ReviewUpdate {
	ru.mutation.ResetRating()
	ru.mutation.SetRating(i)
	return ru
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (ru *ReviewUpdate) SetNillableRating(i *int32) *ReviewUpdate {
	if i != nil {
		ru.SetRating(*i)
	}
	return ru
}

// AddRating adds i to the "rating" field.
func (ru *ReviewUpdate) AddRating(i int32) *ReviewUpdate {
	ru.mutation.AddRating(i)
	return ru
}

// SetProductID sets the "product" edge to the Product entity by ID.
func (ru *ReviewUpdate) SetProductID(id string) *ReviewUpdate {
	ru.mutation.SetProductID(id)
	return ru
}

// SetNillableProductID sets the "product" edge to the Product entity by ID if the given value is not nil.
func (ru *ReviewUpdate) SetNillableProductID(id *string) *ReviewUpdate {
	if id != nil {
		ru = ru.SetProductID(*id)
	}
	return ru
}

// SetProduct sets the "product" edge to the Product entity.
func (ru *ReviewUpdate) SetProduct(p *Product) *ReviewUpdate {
	return ru.SetProductID(p.ID)
}

// Mutation returns the ReviewMutation object of the builder.
func (ru *ReviewUpdate) Mutation() *ReviewMutation {
	return ru.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (ru *ReviewUpdate) ClearProduct() *ReviewUpdate {
	ru.mutation.ClearProduct()
	return ru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *ReviewUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *ReviewUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *ReviewUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *ReviewUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ru *ReviewUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(review.Table, review.Columns, sqlgraph.NewFieldSpec(review.FieldID, field.TypeString))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.FirstName(); ok {
		_spec.SetField(review.FieldFirstName, field.TypeString, value)
	}
	if value, ok := ru.mutation.LastName(); ok {
		_spec.SetField(review.FieldLastName, field.TypeString, value)
	}
	if value, ok := ru.mutation.ReviewText(); ok {
		_spec.SetField(review.FieldReviewText, field.TypeString, value)
	}
	if value, ok := ru.mutation.Rating(); ok {
		_spec.SetField(review.FieldRating, field.TypeInt32, value)
	}
	if value, ok := ru.mutation.AddedRating(); ok {
		_spec.AddField(review.FieldRating, field.TypeInt32, value)
	}
	if ru.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.ProductTable,
			Columns: []string{review.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.ProductTable,
			Columns: []string{review.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{review.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// ReviewUpdateOne is the builder for updating a single Review entity.
type ReviewUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReviewMutation
}

// SetFirstName sets the "first_name" field.
func (ruo *ReviewUpdateOne) SetFirstName(s string) *ReviewUpdateOne {
	ruo.mutation.SetFirstName(s)
	return ruo
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (ruo *ReviewUpdateOne) SetNillableFirstName(s *string) *ReviewUpdateOne {
	if s != nil {
		ruo.SetFirstName(*s)
	}
	return ruo
}

// SetLastName sets the "last_name" field.
func (ruo *ReviewUpdateOne) SetLastName(s string) *ReviewUpdateOne {
	ruo.mutation.SetLastName(s)
	return ruo
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (ruo *ReviewUpdateOne) SetNillableLastName(s *string) *ReviewUpdateOne {
	if s != nil {
		ruo.SetLastName(*s)
	}
	return ruo
}

// SetReviewText sets the "review_text" field.
func (ruo *ReviewUpdateOne) SetReviewText(s string) *ReviewUpdateOne {
	ruo.mutation.SetReviewText(s)
	return ruo
}

// SetNillableReviewText sets the "review_text" field if the given value is not nil.
func (ruo *ReviewUpdateOne) SetNillableReviewText(s *string) *ReviewUpdateOne {
	if s != nil {
		ruo.SetReviewText(*s)
	}
	return ruo
}

// SetRating sets the "rating" field.
func (ruo *ReviewUpdateOne) SetRating(i int32) *ReviewUpdateOne {
	ruo.mutation.ResetRating()
	ruo.mutation.SetRating(i)
	return ruo
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (ruo *ReviewUpdateOne) SetNillableRating(i *int32) *ReviewUpdateOne {
	if i != nil {
		ruo.SetRating(*i)
	}
	return ruo
}

// AddRating adds i to the "rating" field.
func (ruo *ReviewUpdateOne) AddRating(i int32) *ReviewUpdateOne {
	ruo.mutation.AddRating(i)
	return ruo
}

// SetProductID sets the "product" edge to the Product entity by ID.
func (ruo *ReviewUpdateOne) SetProductID(id string) *ReviewUpdateOne {
	ruo.mutation.SetProductID(id)
	return ruo
}

// SetNillableProductID sets the "product" edge to the Product entity by ID if the given value is not nil.
func (ruo *ReviewUpdateOne) SetNillableProductID(id *string) *ReviewUpdateOne {
	if id != nil {
		ruo = ruo.SetProductID(*id)
	}
	return ruo
}

// SetProduct sets the "product" edge to the Product entity.
func (ruo *ReviewUpdateOne) SetProduct(p *Product) *ReviewUpdateOne {
	return ruo.SetProductID(p.ID)
}

// Mutation returns the ReviewMutation object of the builder.
func (ruo *ReviewUpdateOne) Mutation() *ReviewMutation {
	return ruo.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (ruo *ReviewUpdateOne) ClearProduct() *ReviewUpdateOne {
	ruo.mutation.ClearProduct()
	return ruo
}

// Where appends a list predicates to the ReviewUpdate builder.
func (ruo *ReviewUpdateOne) Where(ps ...predicate.Review) *ReviewUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *ReviewUpdateOne) Select(field string, fields ...string) *ReviewUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Review entity.
func (ruo *ReviewUpdateOne) Save(ctx context.Context) (*Review, error) {
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *ReviewUpdateOne) SaveX(ctx context.Context) *Review {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *ReviewUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *ReviewUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ruo *ReviewUpdateOne) sqlSave(ctx context.Context) (_node *Review, err error) {
	_spec := sqlgraph.NewUpdateSpec(review.Table, review.Columns, sqlgraph.NewFieldSpec(review.FieldID, field.TypeString))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Review.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, review.FieldID)
		for _, f := range fields {
			if !review.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != review.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.FirstName(); ok {
		_spec.SetField(review.FieldFirstName, field.TypeString, value)
	}
	if value, ok := ruo.mutation.LastName(); ok {
		_spec.SetField(review.FieldLastName, field.TypeString, value)
	}
	if value, ok := ruo.mutation.ReviewText(); ok {
		_spec.SetField(review.FieldReviewText, field.TypeString, value)
	}
	if value, ok := ruo.mutation.Rating(); ok {
		_spec.SetField(review.FieldRating, field.TypeInt32, value)
	}
	if value, ok := ruo.mutation.AddedRating(); ok {
		_spec.AddField(review.FieldRating, field.TypeInt32, value)
	}
	if ruo.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.ProductTable,
			Columns: []string{review.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.ProductTable,
			Columns: []string{review.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Review{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{review.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
