// Code generated by ent, DO NOT EDIT.

package review

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/eroshiva/cloudtalk/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Review {
	return predicate.Review(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Review {
	return predicate.Review(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Review {
	return predicate.Review(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Review {
	return predicate.Review(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Review {
	return predicate.Review(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Review {
	return predicate.Review(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Review {
	return predicate.Review(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Review {
	return predicate.Review(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Review {
	return predicate.Review(sql.FieldContainsFold(FieldID, id))
}

// FirstName applies equality check predicate on the "first_name" field. It's identical to FirstNameEQ.
func FirstName(v string) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldFirstName, v))
}

// LastName applies equality check predicate on the "last_name" field. It's identical to LastNameEQ.
func LastName(v string) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldLastName, v))
}

// ReviewText applies equality check predicate on the "review_text" field. It's identical to ReviewTextEQ.
func ReviewText(v string) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldReviewText, v))
}

// Rating applies equality check predicate on the "rating" field. It's identical to RatingEQ.
func Rating(v int32) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldRating, v))
}

// FirstNameEQ applies the EQ predicate on the "first_name" field.
func FirstNameEQ(v string) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldFirstName, v))
}

// FirstNameNEQ applies the NEQ predicate on the "first_name" field.
func FirstNameNEQ(v string) predicate.Review {
	return predicate.Review(sql.FieldNEQ(FieldFirstName, v))
}

// FirstNameIn applies the In predicate on the "first_name" field.
func FirstNameIn(vs ...string) predicate.Review {
	return predicate.Review(sql.FieldIn(FieldFirstName, vs...))
}

// FirstNameNotIn applies the NotIn predicate on the "first_name" field.
func FirstNameNotIn(vs ...string) predicate.Review {
	return predicate.Review(sql.FieldNotIn(FieldFirstName, vs...))
}

// FirstNameGT applies the GT predicate on the "first_name" field.
func FirstNameGT(v string) predicate.Review {
	return predicate.Review(sql.FieldGT(FieldFirstName, v))
}

// FirstNameGTE applies the GTE predicate on the "first_name" field.
func FirstNameGTE(v string) predicate.Review {
	return predicate.Review(sql.FieldGTE(FieldFirstName, v))
}

// FirstNameLT applies the LT predicate on the "first_name" field.
func FirstNameLT(v string) predicate.Review {
	return predicate.Review(sql.FieldLT(FieldFirstName, v))
}

// FirstNameLTE applies the LTE predicate on the "first_name" field.
func FirstNameLTE(v string) predicate.Review {
	return predicate.Review(sql.FieldLTE(FieldFirstName, v))
}

// FirstNameContains applies the Contains predicate on the "first_name" field.
func FirstNameContains(v string) predicate.Review {
	return predicate.Review(sql.FieldContains(FieldFirstName, v))
}

// FirstNameHasPrefix applies the HasPrefix predicate on the "first_name" field.
func FirstNameHasPrefix(v string) predicate.Review {
	return predicate.Review(sql.FieldHasPrefix(FieldFirstName, v))
}

// FirstNameHasSuffix applies the HasSuffix predicate on the "first_name" field.
func FirstNameHasSuffix(v string) predicate.Review {
	return predicate.Review(sql.FieldHasSuffix(FieldFirstName, v))
}

// FirstNameEqualFold applies the EqualFold predicate on the "first_name" field.
func FirstNameEqualFold(v string) predicate.Review {
	return predicate.Review(sql.FieldEqualFold(FieldFirstName, v))
}

// FirstNameContainsFold applies the ContainsFold predicate on the "first_name" field.
func FirstNameContainsFold(v string) predicate.Review {
	return predicate.Review(sql.FieldContainsFold(FieldFirstName, v))
}

// LastNameEQ applies the EQ predicate on the "last_name" field.
func LastNameEQ(v string) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldLastName, v))
}

// LastNameNEQ applies the NEQ predicate on the "last_name" field.
func LastNameNEQ(v string) predicate.Review {
	return predicate.Review(sql.FieldNEQ(FieldLastName, v))
}

// LastNameIn applies the In predicate on the "last_name" field.
func LastNameIn(vs ...string) predicate.Review {
	return predicate.Review(sql.FieldIn(FieldLastName, vs...))
}

// LastNameNotIn applies the NotIn predicate on the "last_name" field.
func LastNameNotIn(vs ...string) predicate.Review {
	return predicate.Review(sql.FieldNotIn(FieldLastName, vs...))
}

// LastNameGT applies the GT predicate on the "last_name" field.
func LastNameGT(v string) predicate.Review {
	return predicate.Review(sql.FieldGT(FieldLastName, v))
}

// LastNameGTE applies the GTE predicate on the "last_name" field.
func LastNameGTE(v string) predicate.Review {
	return predicate.Review(sql.FieldGTE(FieldLastName, v))
}

// LastNameLT applies the LT predicate on the "last_name" field.
func LastNameLT(v string) predicate.Review {
	return predicate.Review(sql.FieldLT(FieldLastName, v))
}

// LastNameLTE applies the LTE predicate on the "last_name" field.
func LastNameLTE(v string) predicate.Review {
	return predicate.Review(sql.FieldLTE(FieldLastName, v))
}

// LastNameContains applies the Contains predicate on the "last_name" field.
func LastNameContains(v string) predicate.Review {
	return predicate.Review(sql.FieldContains(FieldLastName, v))
}

// LastNameHasPrefix applies the HasPrefix predicate on the "last_name" field.
func LastNameHasPrefix(v string) predicate.Review {
	return predicate.Review(sql.FieldHasPrefix(FieldLastName, v))
}

// LastNameHasSuffix applies the HasSuffix predicate on the "last_name" field.
func LastNameHasSuffix(v string) predicate.Review {
	return predicate.Review(sql.FieldHasSuffix(FieldLastName, v))
}

// LastNameEqualFold applies the EqualFold predicate on the "last_name" field.
func LastNameEqualFold(v string) predicate.Review {
	return predicate.Review(sql.FieldEqualFold(FieldLastName, v))
}

// LastNameContainsFold applies the ContainsFold predicate on the "last_name" field.
func LastNameContainsFold(v string) predicate.Review {
	return predicate.Review(sql.FieldContainsFold(FieldLastName, v))
}

// ReviewTextEQ applies the EQ predicate on the "review_text" field.
func ReviewTextEQ(v string) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldReviewText, v))
}

// ReviewTextNEQ applies the NEQ predicate on the "review_text" field.
func ReviewTextNEQ(v string) predicate.Review {
	return predicate.Review(sql.FieldNEQ(FieldReviewText, v))
}

// ReviewTextIn applies the In predicate on the "review_text" field.
func ReviewTextIn(vs ...string) predicate.Review {
	return predicate.Review(sql.FieldIn(FieldReviewText, vs...))
}

// ReviewTextNotIn applies the NotIn predicate on the "review_text" field.
func ReviewTextNotIn(vs ...string) predicate.Review {
	return predicate.Review(sql.FieldNotIn(FieldReviewText, vs...))
}

// ReviewTextGT applies the GT predicate on the "review_text" field.
func ReviewTextGT(v string) predicate.Review {
	return predicate.Review(sql.FieldGT(FieldReviewText, v))
}

// ReviewTextGTE applies the GTE predicate on the "review_text" field.
func ReviewTextGTE(v string) predicate.Review {
	return predicate.Review(sql.FieldGTE(FieldReviewText, v))
}

// ReviewTextLT applies the LT predicate on the "review_text" field.
func ReviewTextLT(v string) predicate.Review {
	return predicate.Review(sql.FieldLT(FieldReviewText, v))
}

// ReviewTextLTE applies the LTE predicate on the "review_text" field.
func ReviewTextLTE(v string) predicate.Review {
	return predicate.Review(sql.FieldLTE(FieldReviewText, v))
}

// ReviewTextContains applies the Contains predicate on the "review_text" field.
func ReviewTextContains(v string) predicate.Review {
	return predicate.Review(sql.FieldContains(FieldReviewText, v))
}

// ReviewTextHasPrefix applies the HasPrefix predicate on the "review_text" field.
func ReviewTextHasPrefix(v string) predicate.Review {
	return predicate.Review(sql.FieldHasPrefix(FieldReviewText, v))
}

// ReviewTextHasSuffix applies the HasSuffix predicate on the "review_text" field.
func ReviewTextHasSuffix(v string) predicate.Review {
	return predicate.Review(sql.FieldHasSuffix(FieldReviewText, v))
}

// ReviewTextEqualFold applies the EqualFold predicate on the "review_text" field.
func ReviewTextEqualFold(v string) predicate.Review {
	return predicate.Review(sql.FieldEqualFold(FieldReviewText, v))
}

// ReviewTextContainsFold applies the ContainsFold predicate on the "review_text" field.
func ReviewTextContainsFold(v string) predicate.Review {
	return predicate.Review(sql.FieldContainsFold(FieldReviewText, v))
}

// RatingEQ applies the EQ predicate on the "rating" field.
func RatingEQ(v int32) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldRating, v))
}

// RatingNEQ applies the NEQ predicate on the "rating" field.
func RatingNEQ(v int32) predicate.Review {
	return predicate.Review(sql.FieldNEQ(FieldRating, v))
}

// RatingIn applies the In predicate on the "rating" field.
func RatingIn(vs ...int32) predicate.Review {
	return predicate.Review(sql.FieldIn(FieldRating, vs...))
}

// RatingNotIn applies the NotIn predicate on the "rating" field.
func RatingNotIn(vs ...int32) predicate.Review {
	return predicate.Review(sql.FieldNotIn(FieldRating, vs...))
}

// RatingGT applies the GT predicate on the "rating" field.
func RatingGT(v int32) predicate.Review {
	return predicate.Review(sql.FieldGT(FieldRating, v))
}

// RatingGTE applies the GTE predicate on the "rating" field.
func RatingGTE(v int32) predicate.Review {
	return predicate.Review(sql.FieldGTE(FieldRating, v))
}

// RatingLT applies the LT predicate on the "rating" field.
func RatingLT(v int32) predicate.Review {
	return predicate.Review(sql.FieldLT(FieldRating, v))
}

// RatingLTE applies the LTE predicate on the "rating" field.
func RatingLTE(v int32) predicate.Review {
	return predicate.Review(sql.FieldLTE(FieldRating, v))
}

// HasProduct applies the HasEdge predicate on the "product" edge.
func HasProduct() predicate.Review {
	return predicate.Review(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProductTable, ProductColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductWith applies the HasEdge predicate on the "product" edge with a given conditions (other predicates).
func HasProductWith(preds ...predicate.Product) predicate.Review {
	return predicate.Review(func(s *sql.Selector) {
		step := newProductStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Review) predicate.Review {
	return predicate.Review(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Review) predicate.Review {
	return predicate.Review(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Review) predicate.Review {
	return predicate.Review(sql.NotPredicates(p))
}
